CREATE TABLE IF NOT EXISTS homebrews (
    pid INTEGER,
    id TEXT,
    name TEXT,
    desc TEXT,
    image TEXT,
    package TEXT,
    version TEXT,
    picpath TEXT,
    desc_1 TEXT,
    desc_2 TEXT,
    ReviewStars REAL,
    Size INTEGER,
    Author TEXT,
    apptype TEXT,
    pv TEXT,
    main_icon_path TEXT,
    main_menu_pic TEXT,
    releaseddate TEXT,
    number_of_downloads INTEGER NOT NULL DEFAULT 0,
    github TEXT,
    video TEXT,
    twitter TEXT,
    md5 TEXT
);