from __future__ import annotations

from typing import Protocol


class LoggerPort(Protocol):
    def debug(self, msg: object, *args: object) -> None: ...

    def info(self, msg: object, *args: object) -> None: ...

    def warning(self, msg: object, *args: object) -> None: ...

    def error(self, msg: object, *args: object) -> None: ...

    def exception(self, msg: object, *args: object) -> None: ...
